[2024-10-25 22:29:04] [PID 24476] Exception while deleting user 'admin_user_7': HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /users/pk/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FAC8AD02C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[2024-10-25 22:29:04] [PID 24476] User 'admin_user_7' waiting for 291.41 seconds before next action...
[2024-10-25 22:29:06] [PID 18528] User 'provider_user_8' performing action 'delete_user'...
[2024-10-25 22:29:06] [PID 18528] Skipping deletion for 'provider_user_8' as no valid credentials are available.
[2024-10-25 22:29:06] [PID 18528] User 'provider_user_8' waiting for 268.55 seconds before next action...
